CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME CHAR(256),
    LAST_NAME CHAR(256),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS CARS (
    CAR_ID INT GENERATED ALWAYS AS IDENTITY,
    CAR_MAKE CHAR(128),
    CAR_MODEL CHAR(128),
    CAR_YEAR TIMESTAMP,
    OWNER_ID INT,
    PRIMARY KEY(CAR_ID),
    CONSTRAINT FK_OWNER_ID
      FOREIGN KEY(OWNER_ID)
	  REFERENCES USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS CAR_RESERVATIONS (
    CAR_RESERVATION_ID INT GENERATED ALWAYS AS IDENTITY,
    CAR_ID INT,
    RENTER INT,
    REQUEST_DATA TIMESTAMP,
    RESERVATION_START_DATE TIMESTAMP,
    RESERVATION_END_DATE TIMESTAMP,
    PRICE DOUBLE PRECISION,
    PRIMARY KEY(CAR_RESERVATION_ID),
    CONSTRAINT FK_RENTER
      FOREIGN KEY(RENTER)
	  REFERENCES USERS(USER_ID),
	 CONSTRAINT FK_CAR_ID
      FOREIGN KEY (CAR_ID)
	  REFERENCES CARS(CAR_ID)
);